### ISSUE TITLE
Admin panel

### ISSUE THREAD

**Issue by arkadiuszpalka** [valueadd-poland/pimp-my-pr#105]
As a user after login, I want to go to admin panel and I have two tabs - 'Repository settings' and 'Common settings'.

### Subtasks:
- [ ] #114

**Comment by Sikora00** [comment]
Wg mnie mamy dwie opcje:

1. Tab do przejścia do admin palnelu. Gdy jesteś na admin panelu navigacja w sidebarze zmienia context czyli możesz nawigować się do innych miejsc. Plus możesz wrócić na główne widoki.
2. Rezygnacja z pojęcia admin panelu, po prostu nowe routy w sidebarze.
