### ISSUE TITLE
Reviewers' statistics notification

### ISSUE THREAD

**Issue by arkadiuszpalka** [valueadd-poland/pimp-my-pr#110]
As user at reviewers' statistics, I want to see stripe at list's row where any type of notification appears, additionally I want to see notification at list's row next to the value with a warning.

Show a notification if a reviewer has to check more PRs than are specified in Common warning points #215 
Show a notification if the longest waiting PR is waiting longer than it is specified for its repository. #216

**Comment by Sikora00** [comment]
Needs #215

**Comment by maciejBart99** [comment]
I will do this
