### ISSUE TITLE
Timeline statistics

### ISSUE THREAD

**Issue by Sikora00** [valueadd-poland/pimp-my-pr#160]
Display how the number of prs changed over time.
Maybe display also how many reviewers worked this time and how complex these prs were.
F. ex. in form like:
![image](https://user-images.githubusercontent.com/24508253/79572290-f9b7ca00-80bc-11ea-98d0-960ed3336b67.png)

![image](https://user-images.githubusercontent.com/24508253/79572604-85c9f180-80bd-11ea-8b35-b996ab948bb2.png)

**Comment by MaciejSikorski** [comment]
Liczba pull requestów i średni czas czekania

**Comment by Errancer** [comment]
I started working on the backend part of it.

**Comment by maciejBart99** [comment]
I ve started backend
