### ISSUE TITLE
[FEAT] Common warning points

### ISSUE THREAD

**Issue by Sikora00** [valueadd-poland/pimp-my-pr#215]
**Is your feature request related to a problem? Please describe.**
I want to define breaking points for data not related to any repository like that for reviewers.

**Describe the solution you'd like**
A page where I can define my  warning points. 
I need to define values like:
- Max Pending PRs for a reviewer
- Max Sum of time PRs are waiting for a review from the reviewer

**Comment by maciejBart99** [comment]
I will do this
