### ISSUE TITLE
When should we load the data about projects?

### ISSUE THREAD

**Issue by MaciejSikorski** [valueadd-poland/pimp-my-pr#26]
We can load all the data during login, but we need to logout and login to update our information and
we will duplicate that information in our db.

**Comment by wjanaszek** [comment]
I think we should load data about projects directly after login - and data about projects stored in database should be always the newest ones (without duplicates).
My proposal:
1. Refresh projects list button (to manually trigger refreshing list of projects)
2. Load projects list directly after login

**Comment by MaciejSikorski** [comment]
Pimp my Pr class diagram
https://www.draw.io/#G1eUzbNT2zW3CJf0BSit48jdhto3qVKfP9
